### ISSUE TITLE
Discord Server link

### ISSUE THREAD

**Issue by Traxis** [Nanquitas/CTRPluginFramework-BlankTemplate#2]
Hi,

Sorry to bother you with this, but your Discord invite link doesn't work anymore. Could you please update it? I would like to join. Thank you!

**Comment by Nanquitas** [comment]
Hey :)

Sorry for the inconvenience, I forgot to update it in all the projects.
It's now done, thanks. ;)

Here the new link btw: https://discord.gg/z4ZMh27
